import type { ClientInformation } from "./consultation";

/**
 * Individual answer selected during Guided Discovery.
 *
 * This preserves the decision path followed by the visitor.
 */
export interface DiscoveryAnswerPayload {
  questionId: string;

  question: string;

  optionId: string;

  answer: string;
}

/**
 * Recommendation selected by Guided Discovery.
 *
 * This identifies the practice area and recommendation
 * that the visitor was guided toward.
 */
export interface ConsultationRecommendationPayload {
  practiceArea: string;

  title: string;

  slug: string;
}

/**
 * Consultation preparation generated by IntelliFlow's
 * rules-based Guided Discovery engine.
 */
export interface ConsultationPreparationPayload {
  summary: string[];

  consultationBenefits: string[];

  documents: string[];

  discussionPoints: string[];

  consultationFocus: string[];

  disclaimer?: string;

  estimatedDuration?: string;

  urgencyLevel?: "low" | "medium" | "high";
}

/**
 * Metadata associated with the consultation submission.
 */
export interface ConsultationMetadataPayload {
  source: "guided-discovery";

  submittedAt: string;

  version: string;
}

/**
 * API submission DTO.
 *
 * This represents the data sent from the VIKALP
 * Guided Discovery frontend to the consultation service.
 *
 * It is intentionally separate from the canonical
 * IntelliFlow Consultation domain model.
 */
export interface ConsultationPayload {
  contact: ClientInformation;

  discoveryAnswers: DiscoveryAnswerPayload[];

  recommendation: ConsultationRecommendationPayload;

  preparation: ConsultationPreparationPayload;

  metadata: ConsultationMetadataPayload;
}

export interface ConsultationSubmissionResponse {
  success: boolean;

  referenceNumber: string;
}