/**
 * ==========================================================
 * IntelliFlow Consultation Model
 * ----------------------------------------------------------
 * Canonical data model used throughout IntelliFlow.
 *
 * This object represents ONE completed Guided Discovery.
 *
 * Current Implementation:
 * - VIKALP Advocates & Legal Consultants
 *
 * Future Implementations:
 * - Healthcare
 * - Schools
 * - Hotels
 * - Immigration
 * - Insurance
 * - Finance
 *
 * This model intentionally contains NO React/UI logic.
 * ==========================================================
 */

export type ContactMethod =
  | "phone"
  | "whatsapp"
  | "email";

export type PreferredTime =
  | "morning"
  | "afternoon"
  | "evening"
  | "anytime";

export interface ConsultationRequestFormData {
  preferredContactMethod: ContactMethod;
  preferredContactTime: PreferredTime;
  additionalInformation: string;
}

export type ConsultationStatus =
  | "draft"
  | "submitted"
  | "assigned"
  | "contacted"
  | "completed"
  | "closed";

export interface DiscoveryAnswer {
  questionId: string;

  question: string;

  optionId: string;

  answer: string;
}

export interface ConsultationPreparation {
  practiceArea: string;

  slug: string;

  summary: string[];

  helpfulDocuments: string[];

  discussionPoints: string[];

  consultationFocus: string[];

  disclaimer: string;
}

export interface ClientInformation {
  fullName: string;

  phoneNumber: string;

  email?: string;

  city?: string;

  preferredContactMethod: ContactMethod;

  preferredContactTime: PreferredTime;

  additionalInformation?: string;
}



export interface SubmissionMetadata {
  referenceNumber: string;

  submittedAt: string;

  source: string;

  workflowVersion: string;

  status: ConsultationStatus;
}

export interface Consultation {
  /**
   * Unique identifier
   * Generated by backend later.
   */
  id: string;

  /**
   * Client Information
   */
  client: ClientInformation;

  /**
   * Every answer selected during Guided Discovery.
   */
  discoveryAnswers: DiscoveryAnswer[];

  /**
   * Consultation Preparation generated by IntelliFlow.
   */
  preparation: ConsultationPreparation;

  /**
   * Submission metadata.
   */
  metadata: SubmissionMetadata;
}